services:
  pgsql:
    image: postgres:18
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
#  mysql:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql 
#      MYSQL_DATABASE: mysql
#      MYSQL_USER: mysql
#      MYSQL_PASSWORD: mysql
  php:
    image: allfunc/pmvc-phpunit:8.5
    working_dir: /var/www/html/orm/demos
    command: sleep infinity
    depends_on:
    - pgsql
    volumes:
    - ./:/var/www/html/orm:delegated
  adminer:
    image: adminer
    ports:
      - "9280:8080"
    volumes:
    - ./demos/test.sqlite:/tmp/test.sqlite:delegated
    - ./docker/login.php:/var/www/html/plugins-enabled/login.php:delegated

